@startuml credit-C
skinparam BackgroundColor #lightgrey
participant "Abraham" as A #yellow
participant "Bethany" as B #orange
participant "Chad" as C #lightgreen
participant "Dorus" as D #red
participant "Money" as M #goldenrod
M -[#orange]> C: Loan
C -[#orange]> B: Money
B -[#orange]> C: Carrot
D -[#lightgreen]> C: Money
C -[#lightgreen]> D: Durian
C -[#orange]> M: Repayment
@enduml
