@startuml credit-A
skinparam BackgroundColor #lightgrey
participant "Abraham" as A #yellow
participant "Bethany" as B #orange
participant "Chad" as C #lightgreen
participant "Dorus" as D #red
participant "Money" as M #goldenrod
B -[#yellow]> A: Money
A -[#yellow]> B: Banana
A -[#yellow]> M: Savings
M -[#yellow]> A: Withdrawal
A -[#red]> D: Money
D -[#red]> A: Apple
@enduml
